.TH RECOVERMOV "1" "January 2010" "recovermov" "User Commands"
.SH NAME
recovermov \- recover movies from a filesystem image
.SH SYNOPSIS
.B recovermov
[options] device
.SH DESCRIPTION
.B Recovermov
tries to identify mov movies from a filesystem image. To achieve
this goal, it scans the filesystem image and looks for a mov structure at
blocks starting at 512 bytes boundaries.

.SH OPTIONS
.TP
.B \-h
Display an help message.
.TP
.B \-b blocksize
Set the size of blocks in bytes. On most file systems, setting it to
512 (the default) will work fine as any large file will be stored on
512 bytes boundaries. Setting it to 1 maximize the chances of
finding very small files if the filesystems aggregates them (UFS
for example) at the expense of a much longer running time.
.TP
.B \-i integerindex
Set the initial index value for image numbering (default: 0).
.TP
.B \-n basename
Basename to use to create the salvaged files. Default is
\fIvideo_\fP.
.TP
.B \-V
Display program version and exit.

.P
All the sizes may be suffixed by a \fIk\fP, \fIm\fP or \fIg\fP letter
to indicate KiB, MiB or GiB. For example, 6m correspond to 6 MiB
(6291456 bytes).

.SH EXAMPLES
Recover as many movies as possible from the memory card located in
\fI/dev/sdc\fP:

  recovermov /dev/sdc

Recover as many movies as possible from a crashed ReiserFS file system
(which does not necessarily store files at block boundaries) in
\fI/dev/hdb1\fP:

  recovermov \-b 1 /dev/hdb1

.SH AUTHOR
.B Recovermov
has been written by Jan Funke <jan.funke@inf.tu-dresden.de>.

.SH COPYRIGHT
Copyright (c) 2010-2012 Jan Funke <jan.funke@inf.tu-dresden.de>.
This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

.SH "SEE ALSO"
\fIrecoverjpeg\fP(1)
