#! /bin/sh
#
# This file is part of the recoverjpeg program.
# Copyright (c) 2004-2016 Samuel Tardieu <sam@rfc1149.net>
# http://www.rfc1149.net/devel/recoverjpeg
#
# recoverjpeg is released under the GNU General Public License
# version 2 that you can find in the COPYING file bundled with the
# distribution.
#
# Usage: sort-pictures
# See the sort-pictures manual page for more information.
#

destdir () {
 if identify $1 > /dev/null 2>&1; then
  if [ `wc -c $1 | awk '{print $1}'` -lt 100000 ]; then
   echo small
  else
   dest=`exif -t 0x132 $1 | grep 'Value:' | tail -1 | awk '{print $2}' | tr : -`
   dest=${dest:-undated}
   echo $dest
  fi
 else
  echo invalid
 fi
}

dependencies () {
 echo You need to install the identify and exif programs to use sort-pictures \
   >&2
 exit 1
}

type identify > /dev/null 2>&1 || dependencies
type exif > /dev/null 2>&1 || dependencies

for i in image?????*.jpg; do
 d=`destdir $i`
 mkdir -p $d
 echo $i $d
 ln -f $i $d
done
