#! /usr/bin/python
#
# Usage: remove-duplicates
#
# Remove duplicates of the same file in the current directory if -f is
# given.
#
# If -f is not given, duplicate will be identified twice (once in every
# direction).
#

import os

def check_duplicate(orig, content, copy):
    try:
        if content == open(copy).read():
            print("Removing %s which is a copy of %s" % (copy, orig))
            os.unlink(copy)
    except:
        pass

def aggregate():
    d = {}
    for f in os.listdir('.'):
        s = os.stat(f)[6]
        if s in d: d[s].append(f)
        else: d[s] = [f]
    return d

def remove_duplicates(d):
    for v in sorted(d.values()):
        if len(v) < 2:
            continue
        v.sort()
        for (i, f1) in enumerate(v[:-1]):
            try:
                content = open(f1).read()
                for f2 in v[i+1:]:
                    check_duplicate(f1, content, f2)
            except IOError:
                continue

if __name__ == '__main__':
    remove_duplicates(aggregate())
